name: Run basic features tests on CPU

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with: 
          repository: 'AUTOMATIC1111/stable-diffusion-webui'
          path: 'stable-diffusion-webui'
          
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          repository: 'Mikubill/sd-webui-controlnet'
          path: 'stable-diffusion-webui/extensions/sd-webui-controlnet'
          
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.6
          cache: pip
          cache-dependency-path: |
            **/requirements*txt
            stable-diffusion-webui/requirements*txt
            
      - run: |
          curl -Lo torch-2.0.1+cpu-cp310-cp310-linux_x86_64.whl https://download.pytorch.org/whl/cpu/torch-2.0.1%2Bcpu-cp310-cp310-linux_x86_64.whl
          curl -Lo torchvision-0.15.2+cpu-cp310-cp310-linux_x86_64.whl https://download.pytorch.org/whl/cpu/torchvision-0.15.2%2Bcpu-cp310-cp310-linux_x86_64.whl
          pip install torch-2.0.1+cpu-cp310-cp310-linux_x86_64.whl
          pip install torchvision-0.15.2+cpu-cp310-cp310-linux_x86_64.whl
          curl -Lo stable-diffusion-webui/extensions/sd-webui-controlnet/models/control_canny-fp16.safetensors https://huggingface.co/webui/ControlNet-modules-safetensors/resolve/main/control_canny-fp16.safetensors
          cd stable-diffusion-webui && python launch.py --no-half --disable-opt-split-attention --use-cpu all --skip-torch-cuda-test --api --tests ./extensions/sd-webui-controlnet/tests
          rm -fr stable-diffusion-webui/extensions/sd-webui-controlnet/models/control_canny-fp16.safetensors
          rm -fr *.whl
